### ISSUE TITLE
Imported: Treat Test Timeouts better

### ISSUE THREAD

**Issue by DaGeRe** [DaGeRe/issuetest#25]
> This issue has been imported from an old repository. It was originally created by @Schattensilber at 2021-07-22T13:43:59Z with number #25

Timeout for tests are a supported feature to cut short unexpectedly long running tests.
Currently they seem to simply lead to an error in the peass process, badly visible for the user. Instead it should inform of the issue clearly and continue running any other tests.

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-07-22T13:47:52Z

Could you provide the stacktrace of the error that occured in the Peass process?

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-08-07T15:37:44Z

This error seems to consist of two parts:
- If a measurement VM exits unsucessfully (and has time left to write a XML result file, but not to cleanup data), Peass does not recognize the missing measurement data and just goes on.
- Internally, Peass has read every file in the measurement result folder, even leftover temporary files. Therefore, the error occured.

Hopefully, I fixed both with https://github.com/DaGeRe/peass/commit/881fe7a45fa5c24ee796477b0b340e050bfb65fa . Could you try this again with your configuration?

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-08-08T17:58:09Z

The reason for the failure internally was an error in the KoPeMe execution:

> java.lang.RuntimeException: thread waiting for the response was interrupted
>         at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:849)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:283)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
>         at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1654)
>         at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1639)
>         at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:963)
>         at immo.geomap.tools.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:564)
>         at immo.geomap.tools.elasticsearch.ElasticsearchClient.createIndexIfNotExists(ElasticsearchClient.java:699)
>         at immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl.setup(TestObjektServiceImpl.java:83)
>         at sun.reflect.GeneratedMethodAccessor539.invoke(Unknown Source)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
>         at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
>         at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
>         at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
>         at de.dagere.kopeme.junit.rule.KoPeMeRule$1.run(KoPeMeRule.java:52)
>         at de.dagere.kopeme.junit.rule.KoPeMeBasicStatement.runAllRepetitions(KoPeMeBasicStatement.java:165)
>         at de.dagere.kopeme.junit.rule.KoPeMeBasicStatement.runMainExecution(KoPeMeBasicStatement.java:132)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.runWarmup(KoPeMeStandardRuleStatement.java:100)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.executeSimpleTest(KoPeMeStandardRuleStatement.java:79)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement.access$000(KoPeMeStandardRuleStatement.java:28)
>         at de.dagere.kopeme.junit.rule.KoPeMeStandardRuleStatement$1.run(KoPeMeStandardRuleStatement.java:45)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.InterruptedException
>         at java.lang.Object.wait(Native Method)
>         at java.lang.Object.wait(Object.java:502)
>         at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:82)
>         at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
>         at org.elasticsearch.client.RestClient.performRequest(RestClient.java:279)
>         ... 25 more
> 
Therefore, an integration test should test that after this exception, measurement is continued correctly.
