### ISSUE TITLE
Imported: Failure in RCA

### ISSUE THREAD

**Issue by DaGeRe** [DaGeRe/issuetest#48]
> This issue has been imported from an old repository. It was originally created by @Schattensilber at 2021-10-20T08:52:56Z with number #48

When executing RCA with
```
measure versionDiff: 1, VMs: 20, 
              createDefaultConstructor: false, executeRCA: true, iterations: 40, 
              executeParallel: false, warmup: 10,
              includes: 'immo.geomap.backend.objektservice.impl.objekte.TestObjektServiceImpl#*',
              measurementMode: 'LEVELWISE', repetitions: 10, testGoal: '', timeout: 100,
              useAggregation: true, useSourceInstrumentation: true, displayRTSLogs: true, nightlyBuild: false,
              redirectToNull: false, showStart: true, excludeLog4j: true, generateCoverageSelection: true
```
                        
In Console view when running:

```
Cannot reduce iterations (5) or repetitions (2) anymore
Was unable to analyze: testSearchPaging
java.lang.RuntimeException: Execution took too long, Iterations: 2 Warmup: 0 Repetitions: 2
   at de.dagere.peass.measurement.rca.CauseTester.measureVersion(CauseTester.java:66)
   at de.dagere.peass.measurement.rca.searcher.LevelCauseSearcher.measureLevel(LevelCauseSearcher.java:99)
   at de.dagere.peass.measurement.rca.searcher.LevelCauseSearcher.isLevelDifferent(LevelCauseSearcher.java:83)
   at de.dagere.peass.measurement.rca.searcher.LevelCauseSearcher.isLevelDifferent(LevelCauseSearcher.java:93)
   at de.dagere.peass.measurement.rca.searcher.LevelCauseSearcher.searchCause(LevelCauseSearcher.java:70)
   at de.dagere.peass.measurement.rca.searcher.CauseSearcher.search(CauseSearcher.java:67)
   at de.dagere.peass.ci.helper.RCAExecutor.executeRCA(RCAExecutor.java:139)
   at de.dagere.peass.ci.helper.RCAExecutor.analyseChange(RCAExecutor.java:119)
   at de.dagere.peass.ci.helper.RCAExecutor.executeRCAs(RCAExecutor.java:72)
   at de.dagere.peass.ci.remote.RemoteRCA.executeRCA(RemoteRCA.java:88)
   at de.dagere.peass.ci.remote.RemoteRCA.invoke(RemoteRCA.java:58)
   at de.dagere.peass.ci.remote.RemoteRCA.invoke(RemoteRCA.java:28)
   at hudson.FilePath.act(FilePath.java:1173)
   at hudson.FilePath.act(FilePath.java:1156)
   at de.dagere.peass.ci.LocalPeassProcessManager.rca(LocalPeassProcessManager.java:98)
   at de.dagere.peass.ci.MeasureVersionBuilder.measure(MeasureVersionBuilder.java:171)
   at de.dagere.peass.ci.MeasureVersionBuilder.runAllSteps(MeasureVersionBuilder.java:155)
   at de.dagere.peass.ci.MeasureVersionBuilder.perform(MeasureVersionBuilder.java:119)
   at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
   at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
```

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-10-20T10:34:04Z

Thanks for the issue, the problem seems to be that enum constructors must not access static fields, and therefore the instrumentation failed. This should be fixed by https://github.com/DaGeRe/peass/commit/c917b2db97a9da37b127046f17a36ce677401be0 Can you confirm this?
