### ISSUE TITLE
Imported: Logs Missing if Errors Occur

### ISSUE THREAD

**Issue by DaGeRe** [DaGeRe/issuetest#52]
> This issue has been imported from an old repository. It was originally created by @mawHBT at 2021-11-01T09:48:53Z with number #52

If KiekerFolderUtil.getClazzMethodFolder(KiekerFolderUtil.java:41) throws RuntimeException, no dependency-reading logs are created.

Stacktrace is:
Caused by: java.lang.RuntimeException: Folder $methodResult is no Kieker result folder!
   at de.dagere.peass.dependency.traces.KiekerFolderUtil.getClazzMethodFolder(KiekerFolderUtil.java:41)
   at de.dagere.peass.dependency.DependencyManager.updateDependenciesOnce(DependencyManager.java:221)
   at de.dagere.peass.dependency.DependencyManager.readInitialResultFiles(DependencyManager.java:182)
   at de.dagere.peass.dependency.DependencyManager.initialyGetTraces(DependencyManager.java:116)
   at de.dagere.peass.dependency.reader.InitialVersionReader.readInitialVersion(InitialVersionReader.java:44)
   at de.dagere.peass.dependency.reader.DependencyReader.readInitialVersion(DependencyReader.java:347)
   at de.dagere.peass.ci.ContinuousDependencyReader.doFullyLoadDependencies(ContinuousDependencyReader.java:188)
   at de.dagere.peass.ci.ContinuousDependencyReader.fullyLoadDependencies(ContinuousDependencyReader.java:177)
   at de.dagere.peass.ci.ContinuousDependencyReader.getDependencies(ContinuousDependencyReader.java:111

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-11-01T09:50:09Z

Could you provide the exact error, so I can fix this? (There might be different types of errors, which, in the future, might require different issues).

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @DaGeRe at 2021-11-03T13:46:10Z

This should be fixed in https://github.com/DaGeRe/peass-ci/commit/eb5d0a0ef7c61dd41f373c7356a06092b7593e12 (so latest develop commit)
@Schattensilber @mawHBT Can you confirm this?

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @Schattensilber at 2021-11-03T13:48:26Z

Yes, works for me.

**Comment by DaGeRe** [comment]
> This comment has been imported from an old repository. It was originally created by @mawHBT at 2021-11-03T14:13:00Z

Works for me also, thank you.
